Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 159, in <module>
    tempOut = readTemp(deviceFileOut)
  File "/home/pi/zend_dht/MeteoStation13.py", line 54, in readTemp
    lines = readTempRaw(devFile)
  File "/home/pi/zend_dht/MeteoStation13.py", line 48, in readTempRaw
    f = open(deviceFile, 'r')
IOError: [Errno 2] No such file or directory: '/sys/bus/w1/devices/28-000006c8044b/w1_slave'
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/zend_dht/MeteoStation13.py", line 26, in <module>
    deviceFolderOut = glob.glob(baseDir + '28-000006c8044b')[0]
IndexError: list index out of range
